[build]
  publish = ".next"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  NEXT_PUBLIC_GA_MEASUREMENT_ID = "G-XXXXXXXXXX"
  NEXT_PUBLIC_GOOGLE_ADS_CONVERSION_ID = "AW-XXXXXXXXX"
